**HOMEWORK WEEK 6**

**NAMA: MARINA IRDAYANTI**

**NIM : 1301174319**

# Exercise

<center><img src = "https://i.imgur.com/a7Lkz1K.png" align = "center"> </center>


**SOAL A**

In [0]:
import numpy as np

def F(X):
  f1 = 3*X[0]**2 - X[1]**2 
  f2 = 3*X[0]*X[1]**2 - (X[0]**3) - 1
  
  return np.array([f1, f2])

def g(X):
  fx = F(X)
  return  fx[0]**2 + fx[1]**2 

def Grad_g(X):
  fx = F(X)

  f1x = 2*fx[0]*(6*X[0]) + 2*fx[1]*((3*X[1]**2)-3*X[0]) 
  f2x = 2*fx[0]*(2*X[1]) + 2*fx[1]*(6*X[0]) 
  
  return np.array([f1x, f2x])

def errorL2(X):
  return  np.sqrt(sum(X**2))

x=[1,1]
TOL = 0.01
N = 100
k = 1

#step 1
k= 1
while (k<=N):   #step 2
  #step 3
  g1 =  g(x)
  Z =  Grad_g(x)
  z0 =  errorL2(Z)
  
  #step 4
  if (z0 ==0):
    print("Zero gradient")
    print(x)
    break;
  #Step 5
  Z  =  Z/z0
  a1 =  0
  a3 =  1
  g3 = g(x-a3*Z) 
  #print(g3)

  #step 6
  while(g3 >= g1):
    #step 7
    a3 =  a3/2
    g3 =  g(x-a3*Z) 
    #Step 8
    if a3 < TOL/2:
      print("No likely improvement")
      print(x)
      break
  #step 9
  a2 =  a3/2
  g2 =  g(x-a2*Z) 

  #step 10
  h1 =  (g2-g1)/a2
  h2 =  (g3-g2)/(a3-a2)
  h3 =  (h2-h1)/a3

  #step 11
  a0 =  0.5*(a2-h1/h3)
  g0 =  g(x-a0*Z) 

  #step 12
  if (g0<g3):
    a = a0
  else:
    a = a3

  gL= g(x-a*Z)
  #Step 13
  x = x - a*Z
  print("{}, {}, {}".format(k,x,g(x)))
  #Step 14
  if abs(gL-g1) < TOL:
    print("done")
    print(x)
    break
  
  k=k+1

1, [0.44459057 0.53715881], 0.586939623484004
2, [0.3376316 0.6822681], 0.3367380273290231
3, [0.41704886 0.90593365], 0.0914456863535715
4, [0.44771387 0.93097321], 0.07595144622297119
5, [0.46651254 0.93990608], 0.07132618133192835
done
[0.46651254 0.93990608]


**SOAL B**

In [0]:
import numpy as np

def F(X):
  f1 = np.log(X[0]**2+X[1]**2)-np.sin(X[0]*X[1])-np.log(2)-np.log(np.pi)
  f2 = np.exp(X[0]-X[1])+np.cos(X[0]*X[1])
  
  return np.array([f1, f2])

def g(X):
  fx = F(X)
  return  fx[0]**2 + fx[1]**2 

def Grad_g(X):
  fx = F(X)

  f1x = 2*fx[0]*(2*X[0]/(X[0]**2+X[1]**2)-np.sin(X[0]-X[1])) + 2*fx[1]*(np.exp(X[0]-X[1])- X[1]*np.sin(X[1]*X[0]))
  f2x = 2*fx[0]*(2*X[1]/(X[0]**2+X[1]**2)-np.sin(X[0]-X[1])) + 2*fx[1]*(-(np.exp(X[0]-X[1])) - X[0]*np.sin(X[0]*X[1])) 
  
  return np.array([f1x, f2x])

def errorL2(X):
  return  np.sqrt(sum(X**2))

x=[1,1]
TOL = 0.01
N = 100
k = 1

#step 1
k= 1
while (k<=N):   #step 2
  #step 3
  g1 =  g(x)
  Z =  Grad_g(x)
  z0 =  errorL2(Z)
  
  #step 4
  if (z0 ==0):
    print("Zero gradient")
    print(x)
    break;
  #Step 5
  Z  =  Z/z0
  a1 =  0
  a3 =  1
  g3 = g(x-a3*Z) 
  #print(g3)

  #step 6
  while(g3 >= g1):
    #step 7
    a3 =  a3/2
    g3 =  g(x-a3*Z) 
    #Step 8
    if a3 < TOL/2:
      print("No likely improvement")
      print(x)
      break
  #step 9
  a2 =  a3/2
  g2 =  g(x-a2*Z) 

  #step 10
  h1 =  (g2-g1)/a2
  h2 =  (g3-g2)/(a3-a2)
  h3 =  (h2-h1)/a3

  #step 11
  a0 =  0.5*(a2-h1/h3)
  g0 =  g(x-a0*Z) 

  #step 12
  if (g0<g3):
    a = a0
  else:
    a = a3

  gL= g(x-a*Z)
  #Step 13
  x = x - a*Z
  print("{}, {}, {}".format(k,x,g(x)))
  #Step 14
  if abs(gL-g1) < TOL:
    print("done")
    print(x)
    break
  
  k=k+1

1, [1.33973341 1.94052178], 0.5019938906520416
2, [1.50017878 2.06913396], 0.18764618885184353
3, [1.72571063 1.77837629], 0.011489509929629053
4, [1.76547894 1.7816355 ], 0.000282758507748353
5, [1.77183666 1.7724671 ], 2.3879404420971327e-06
done
[1.77183666 1.7724671 ]


**SOAL C**

In [0]:
import numpy as np

def F(X):
  f1 = X[0]**3 + (X[0]**2*X[1]) - (X[0]*X[2]) + 6
  f2 = (np.exp(X[0])) + (np.exp(X[1])) - X[2]
  f3 =  X[1]**2 - 2*(X[0]*X[2])**2 - 4
  return np.array([f1, f2, f3])

def g(X):
  fx = F(X)
  return  fx[0]**2 + fx[1]**2 + fx[2]**2 

def Grad_g(X):
  fx = F(X)

  f1x = 2*fx[0]*(3*X[0]**2) + (2*X[0]*X[1]) - (X[2])  + 2*fx[1]*(np.exp(X[0])) + 2*fx[2]*(X[2]**2)
  f2x = 2*fx[0]*(X[0]**2) + 2*fx[1]*(np.exp(X[1])) + 2*fx[2]*(2*X[1])
  f3x = 2*fx[0]*(-X[0]) + 2*fx[1]*(-1) + 2*fx[2]*(-2*(X[0])**2)
  
  return np.array([f1x, f2x, f3x])

def errorL2(X):
  return  np.sqrt(sum(X**2))

x=[-1, -2, 1]
TOL = 0.01
N = 100
k = 1

#step 1
k= 1
while (k<=N):   #step 2
  #step 3
  g1 =  g(x)
  Z  =  Grad_g(x)
  z0 =  errorL2(Z)
  
  #step 4
  if (z0 ==0):
    print("Zero gradient")
    print(x)
    break;
  #Step 5
  Z  =  Z/z0
  a1 =  0
  a3 =  1
  g3 = g(x-a3*Z) 
  #print(g3)

  #step 6
  while(g3 >= g1):
    #step 7
    a3 =  a3/2
    g3 =  g(x-a3*Z) 
    #Step 8
    if a3 < TOL/2:
      print("No likely improvement")
      print(x)
      break
  #step 9
  a2 =  a3/2
  g2 =  g(x-a2*Z) 

  #step 10
  h1 =  (g2-g1)/a2
  h2 =  (g3-g2)/(a3-a2)
  h3 =  (h2-h1)/a3

  #step 11
  a0 =  0.5*(a2-h1/h3)
  g0 =  g(x-a0*Z) 

  #step 12
  if (g0<g3):
    a = a0
  else:
    a = a3

  gL= g(x-a*Z)
  #Step 13
  x = x - a*Z
  print("{}, {}, {}".format(k,x,g(x)))
  #Step 14
  if abs(gL-g1) < TOL:
    print("done")
    print(x)
    break
  
  k=k+1

1, [-1.3078722  -2.32461682  0.76885501], 1.1704198543321858
2, [-1.37682194 -2.37087841  0.72964342], 0.3151663520784168
3, [-1.38134573 -2.37458674  0.72572548], 0.3103124949169247
done
[-1.38134573 -2.37458674  0.72572548]


**SOAL D**

In [2]:
import numpy as np

def F(X):
  f1 =  6*X[0]-(2*np.cos(X[1]*X[2]))-1
  f2 =  9*X[1]+(np.sqrt(X[0]**2+np.sin(X[2])+1.06))+0.9
  f3 =  60*X[2]+3*np.exp(-X[0]*X[1])+(10*np.pi-3)
  return np.array([f1, f2, f3])

def g(X):
  fx = F(X)
  return  fx[0]**2 + fx[1]**2 + fx[2]**2 

def Grad_g(X):
  fx = F(X)

  f1x = 2*fx[0]*(6) + 2*fx[1]*(X[0]/np.sqrt(X[0]**2+np.sin(X[2])+1.06)) + 2*fx[2]*(-3*np.exp(-X[0]*X[1])*X[1])
  f2x = 2*fx[0]*(2*X[2]*np.sin(X[1]*X[2])) + 2*fx[1]*(9) + 2*fx[2]*(-3*np.exp(-X[0]*X[1])*X[0])
  f3x = 2*fx[0]*(2*X[1]*np.sin(X[1]*X[2])) + 2*fx[1]*(0.5*np.cos(X[2])/np.sqrt(X[0]**2+np.sin(X[2])+1.06)) + 2*fx[2]*(60)  
  
  return np.array([f1x, f2x, f3x])

def errorL2(X):
  return  np.sqrt(sum(X**2))

x=[0, 0, 0]
TOL = 0.01
N = 100
k = 1

#step 1
k= 1
while (k<=N):   #step 2
  #step 3
  g1 =  g(x)
  Z =  Grad_g(x)
  z0 =  errorL2(Z)
  
  #step 4
  if (z0 ==0):
    print("Zero gradient")
    print(x)
    break;
  #Step 5
  Z=  Z/z0
  a1 =  0
  a3 =  1
  g3 = g(x-a3*Z) 
  #print(g3)

  #step 6
  while(g3 >= g1):
    #step 7
    a3 =  a3/2
    g3 =  g(x-a3*Z) 
    #Step 8
    if a3 < TOL/2:
      print("No likely improvement")
      print(x)
      break
  #step 9
  a2 =  a3/2
  g2 =  g(x-a2*Z) 

  #step 10
  h1 =  (g2-g1)/a2
  h2 =  (g3-g2)/(a3-a2)
  h3 =  (h2-h1)/a3

  #step 11
  a0 =  0.5*(a2-h1/h3)
  g0 =  g(x-a0*Z) 

  #step 12
  if (g0<g3):
    a = a0
  else:
    a = a3

  gL= g(x-a*Z)
  #Step 13
  x = x - a*Z
  print("{}, {}, {}".format(k,x,g(x)))
  #Step 14
  if abs(gL-g1) < TOL:
    print("done")
    print(x)
    break
  
  k=k+1

1, [ 0.00500072 -0.0048246  -0.52393467], 11.396405631778984
2, [ 0.32822486 -0.26709105 -0.51892192], 1.799754936747469
3, [ 0.32996303 -0.26512946 -0.52872754], 1.4526111616316795
4, [ 0.35170369 -0.24493714 -0.52083531], 1.1795810657599486
5, [ 0.35321543 -0.24355119 -0.52853511], 0.9656117315788508
6, [ 0.37214281 -0.22935332 -0.52226479], 0.7947797659304774
7, [ 0.37344914 -0.22838065 -0.52841066], 0.6585462447454902
8, [ 0.38988757 -0.21853236 -0.52335792], 0.5481731554115082
9, [ 0.39101149 -0.21785387 -0.52834101], 0.45867801749683973
10, [ 0.40525058 -0.21113216 -0.52421443], 0.3851531273244617
11, [ 0.40621469 -0.2106613  -0.52831278], 0.32466329200898386
12, [ 0.41849905 -0.20616661 -0.52490683], 0.2743813856977453
No likely improvement
[ 0.41849905 -0.20616661 -0.52490683]
13, [ 0.41932482 -0.205841   -0.52831429], 0.2325996901820875
14, [ 0.42988506 -0.20290621 -0.52547459], 0.1975419800051821
No likely improvement
[ 0.42988506 -0.20290621 -0.52547459]
15, [ 0.43059171 -0.