In [ ]:
import numpy as np
m = np.array([0.08,0.1,0.06])
print(m)

[0.08 0.1  0.06]


In [ ]:
sigma1 = 1.5
sigma2 = 0.5
sigma3 = 1.2
rho12 = 0.3
rho23 = 0
rho13 =-0.2

In [ ]:
c11=sigma1**2
c22=sigma2**2
c33=sigma3**2
c12=rho12*sigma1*sigma2
c23=rho23*sigma2*sigma3
c13=rho13*sigma1*sigma3

In [ ]:
#mendevinisikan matriks covariansi
C = np.array([[c11,c12,c13],[c12,c22,c23],[c13,c23,c33]])
print(C)

[[ 2.25   0.225 -0.36 ]
 [ 0.225  0.25   0.   ]
 [-0.36   0.     1.44 ]]


In [ ]:
u = np.array([1,1,1])
uT = np.transpose(u)

In [ ]:
from numpy.linalg import inv
Cinvers = inv(C)
print(Cinvers)

[[ 0.51085568 -0.45977011  0.12771392]
 [-0.45977011  4.4137931  -0.11494253]
 [ 0.12771392 -0.11494253  0.72637292]]


In [ ]:
#menghitung bobot portofolio dengan resiko terkecil
wopt = np.dot(u,Cinvers)/(u.dot(Cinvers).dot(uT))
print(wopt)

[0.03758642 0.80703403 0.15537956]


In [ ]:
#menghitung nilai resiko
woptT = np.transpose(wopt)
resiko = wopt.dot(C).dot(woptT)
print(resiko)

0.2102154507013893


In [ ]:
Ek = np.dot(m,woptT)
print(Ek)

0.09303308946909188


# portofolio garis variansi minimum

In [ ]:
#nilai ek diterapkan menjadi syarat, misalnya
muv = 0.1
#portofolio membagi ek = muv dengan resiko terkecil
A1= np.array([[1,u.dot(Cinvers).dot(np.transpose(m))],[muv,m.dot(Cinvers).dot(np.transpose(m))]])
print(A1)

[[1.         0.44256066]
 [0.1        0.04251277]]


In [ ]:
A2 = np.array([[u.dot(Cinvers).dot(uT),1],[m.dot(Cinvers).dot(uT), muv]])
print(A2)

[[4.75702427 1.        ]
 [0.44256066 0.1       ]]


In [ ]:
A3 = np.array([[u.dot(Cinvers).dot(uT),u.dot(Cinvers).dot(np.transpose(m))],[m.dot(Cinvers).dot(uT), m.dot(Cinvers).dot(np.transpose(m))]])
print(A3)

[[4.75702427 0.44256066]
 [0.44256066 0.04251277]]


In [ ]:
from numpy.linalg import det
wopt = (det(A1)*np.dot(u,Cinvers)+ det(A2)*np.dot(m,Cinvers))/(det(A3))
print(wopt)

[-0.03561888  1.01780944  0.01780944]


In [ ]:
#Nilai Resiko
resiko2 = wopt.dot(C).dot(np.transpose(wopt))
print(resiko2)

0.24643811219946413
